### ISSUE TITLE
TODO: Documentation

### ISSUE THREAD

**Issue by jasmin-guven** [meyresearch/metalloenzymes#8]
- [ ] Tutorial document for system preparation
- [ ] Examples for using meze.py
- [ ] Documentation describing code
